### ISSUE TITLE
new url domain

### ISSUE THREAD

**Issue by sabrisangjaya** [YuehaiTeam/webstatic-extractor#1]
current web event is started by act.hoyoverse.com and it seems protected by CORS

**Comment by xytoki** [comment]
CORS is only allowed in the Chinese site of hoyoverse/mihoyo, so just find the corresponding url in the Chinese version and fill it in.
For example, act.hoyoverse.com ( or webstatic-sea.mihoyo.com ) , is webstatic.mihoyo.com in the Chinese version.

**Comment by Zhaokugua** [comment]
> CORS is only allowed in the Chinese site of hoyoverse/mihoyo, so just find the corresponding url in the Chinese version and fill it in. For example, act.hoyoverse.com ( or webstatic-sea.mihoyo.com ) , is webstatic.mihoyo.com in the Chinese version.

佬，我试着提取最新穹轨的活动页面也遇到CORS问题了
https://act.mihoyo.com/sr/event/e20231018version-5kx3qh/index.html

I've got the same problom in the Chinese version. 
qwq
