### ISSUE TITLE
[Bug]第三方Cookie禁用导致链接下载不了。

### ISSUE THREAD

**Issue by HyBoxwood** [YuehaiTeam/webstatic-extractor#2]
https://webstatic.mihoyo.com/sr/event/e20230105openingh5-qlg2th/index.html

Extracted 5 spine(s), 46 render-related image(s), 21 other resource(s)    Download started...    然后
mitm.html?version=2.0.0:23  GET https://jimmywarting.github.io/StreamSaver.js/ping 404

**Comment by xytoki** [comment]
测了一下可以，应该是StreamSaver的偶发bug？

**Comment by HyBoxwood** [comment]
![image](https://github.com/YuehaiTeam/webstatic-extractor/assets/87700780/405fc3fa-d612-459b-8eb1-583c3fb84dc1)

![Screenshot_20230606_225716](https://github.com/YuehaiTeam/webstatic-extractor/assets/87700780/8ba8d1d5-c668-4e05-b4a4-6ed00d62c59d)
我的电脑和手机都不太行（

**Comment by xytoki** [comment]
你手动打开一下404那个页面看看，如果是404就是streamsaver的问题；手机只支持原版chrome/edge/ff，任何外置下载器或者调用系统下载的都做不了

**Comment by HyBoxwood** [comment]
我找到罪魁祸首了，第三方cookie被禁用了。

**Comment by xytoki** [comment]
> 

ok，我后面做下兼容吧
