### ISSUE TITLE
更新后的webstatic-extractor无法成功下载，只弹出空白网页

### ISSUE THREAD

**Issue by liTongQ** [YuehaiTeam/webstatic-extractor#3]
你好，我想请问一下，为什么更新后的webstatic-extractor在点击下载时会弹出空白网页，无法成功下载？
我已经尝试了webstatic.mihoyo.com和act.mihoyo.com，但都只能弹出一个空白网页。

**Comment by xytoki** [comment]
麻烦给一下下载的网页活动的具体地址，以及是否有显示Error？

**Comment by liTongQ** [comment]
你好，我输入的网址是：3.8「清夏！乐园？大秘境！」的先行页：https://act.mihoyo.com/ys/event/e20230624preview/index.html?game_biz=hk4e_cn&mhy_presentation_style=fullscreen&mhy_landscape=true&mhy_hide_status_bar=true&utm_source=bbs&utm_medium=mys&utm_campaign=arti
没有显示Error，一直显示下载中。
我在电脑上使用不同的浏览器、在手机、平板电脑上使用都是弹出一个新的空白网页，电脑浏览器也清理过了，都只能弹出一个新的空白网页。
![image](https://github.com/YuehaiTeam/webstatic-extractor/assets/78954543/1aec07e4-6c9b-4d3d-88ed-768408e41b96)
![1688105977(1)](https://github.com/YuehaiTeam/webstatic-extractor/assets/78954543/c881f964-878e-4e6c-b5b6-6787364ae6cf)

**Comment by xytoki** [comment]
收到，我测试一下

**Comment by xytoki** [comment]
大概了解原因了，你用的是http访问，后面我会加上强制跳转https

**Comment by liTongQ** [comment]
你好，我看这个小工具的网址有变动，是已经更新完毕了吗？我现在好像连新网址也打不开了。
我是直接点最新的连接打开的，打开后地址栏就变成旧网址了。
![image](https://github.com/YuehaiTeam/webstatic-extractor/assets/78954543/ddeedf71-bfd2-4182-86ea-3a0939a596dc)

**Comment by xytoki** [comment]
服务器挂了，已修

**Comment by xytoki** [comment]
强制https也已经加上了，先close，还有问题就reopen
